version: '3.9'

services:
  postgresDev:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgresDev:/var/lib/postgresql/data'

  postgresTest:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgresTest:/var/lib/postgresql/data'

volumes:
  postgresDev:
  postgresTest:

